// <auto-generated />
using System;
using MEC.ControleRDO.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MEC.ControleRDO.Migrations
{
    [DbContext(typeof(ControleRdoContext))]
    [Migration("20240327015405_TableRdo")]
    partial class TableRdo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MEC.ControleRDO.Models.FiscalModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("Fiscais");
                });

            modelBuilder.Entity("MEC.ControleRDO.Models.ObraModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("FiscalId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.Property<string>("NumeroOrcamento")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("numero_do_orcamento");

                    b.Property<string>("SE")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("SE");

                    b.HasKey("Id");

                    b.HasIndex("FiscalId");

                    b.ToTable("Obras");
                });

            modelBuilder.Entity("MEC.ControleRDO.Models.RdoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<int>("Assinatura")
                        .HasColumnType("int")
                        .HasColumnName("assinatura");

                    b.Property<DateTime?>("DataAssinatura")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_assinatura");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_envio");

                    b.Property<DateTime>("DataRdo")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_rdo");

                    b.Property<long>("ObraId")
                        .HasColumnType("bigint");

                    b.Property<string>("Observacao")
                        .HasColumnType("longtext")
                        .HasColumnName("observacao");

                    b.HasKey("Id");

                    b.HasIndex("ObraId");

                    b.ToTable("Rdos");
                });

            modelBuilder.Entity("MEC.ControleRDO.Models.UsuarioModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("MEC.ControleRDO.Models.ObraModel", b =>
                {
                    b.HasOne("MEC.ControleRDO.Models.FiscalModel", "Fiscal")
                        .WithMany("Obras")
                        .HasForeignKey("FiscalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fiscal");
                });

            modelBuilder.Entity("MEC.ControleRDO.Models.RdoModel", b =>
                {
                    b.HasOne("MEC.ControleRDO.Models.ObraModel", "Obra")
                        .WithMany("Rdos")
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("MEC.ControleRDO.Models.FiscalModel", b =>
                {
                    b.Navigation("Obras");
                });

            modelBuilder.Entity("MEC.ControleRDO.Models.ObraModel", b =>
                {
                    b.Navigation("Rdos");
                });
#pragma warning restore 612, 618
        }
    }
}
